version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - db_secrets.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
